### ISSUE TITLE
Create 'calls' table and Call model

### ISSUE THREAD

**Issue by jessehorne** [Ameelio/connect-api#11]
* scheduled_start
* scheduled_end
* start (when both parties join)
* end (when both parties exit)
* contact_id
* inmate_id
* user_id
* status ("scheduled", "cancelled", "ongoing", "terminated", "completed", "cancelled")
* storage_url (nullable, at first null, then link is set once recording becomes available)
* live_url
* kiosk_id
* inmate_rating (nullable)
* inmate_feedback (nullable)
* user_rating (nullable)
* user_feedback (nullable)

**Comment by dabbler0** [comment]
Questions/notes: 
  - What is the difference between `contact_id` and `user_id`?
  - Potentially change `storage_url` and `live_url` to `storage_identifier` and `live_identifier` in case we want non-http delivery mechanisms or to use this in some other part of the system
  - Potentially make `status` an integer property instead of a string property?
  - Long-term question: do we want to generalize things so that we can have many-to-one calls? (many outside, one inside?) Current model assumes one-to-one. Potentially not a concern if policy forbids this.
